### ISSUE TITLE
Calculate the login time of a station

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#12]
Based on our Game State, create a function (placed in `calculator.js`) that calculates the login time of a station. This function should take two arguments: the game state and station index. It should consider the properties `loginTime` and `loginMultiplier` we've got. It should return an integer that represents the login time in seconds.

**Comment by LudvigStridsberg** [comment]
I only saw this just now. Should I copy and paste the line from the Station login-event into calculator and then update the code in the event so that it calls the function in calculator instead?

**Comment by trumtomte** [comment]
Yes please! But, make the calculator function look like this:

``` js
function getLoginTime(gameState, playerId, stationIndex) {
  // Calculate the login time
}
```

And then, as you said, update the code in the station login event handler 👍🏻
