### ISSUE TITLE
Spell: Reset All (stations + pockets)

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#14]
Create a spell that resets all tokens of all stations and empties all player pockets.

- Event: `spell:reset:all`

This spell should broadcast:

1. Event: `reset:stations` with a payload of `{ stations: [ ... ] }` (which would be all the updated stations and their racks
2. Event: `reset:pockets` with an empty payload

**Comment by trumtomte** [comment]
This should also (later on) broadcast the new "next salary" value for all teams.

**Comment by louiseedstrom** [comment]
Shouldn't the payload for the empty pocket be -1?

**Comment by trumtomte** [comment]
It could be, it's up to us to decide what we want. In the case without a payload, the frontend would simply do the following: when the event `reset:pockets` is received the frontend would empty the players pockets both in the client state and in the UI. With a payload it would, just like you say send out both pockets (the secret one included) as -1, which - would do more or less the same. If we take it another step further maybe it should, instead, broadcast `player:pockets` with a payload of -1 for each of the two pockets. This event could then be reused whenever we want to update a players pockets (or reset it in this case). This would be one emerging pattern that we might encounter later on in our development.

So, for my answer: I'd say lets leave it without a payload for now, and when we have a clear overview of the events we use we might change this so it actually broadcasts the change of the players pockets (your suggestion).
