### ISSUE TITLE
Spell: Double salary

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#19]
Create a spell that *until the next salary* will increase the salary gained from all stations by 50%.

- Event: `spell:stations:double-salary`
- Payload: `{}`

This spell should broadcast `stations:double-salary` with a payload of `{}` to everyone in the game. 

*This broadcast might not be needed in the future.*

**Comment by trumtomte** [comment]
This should also (later on) broadcast the new "next salary" value for all teams.

**Comment by LudvigStridsberg** [comment]
> Create a spell that until the next salary will increase the salary gained from all stations by 50%.

"Double", to me, usually means an increase of 100%, not 50%. Which one should I program?

**Comment by trumtomte** [comment]
You are correct sir, double is 100% (and what you did in your pull request 👍🏻 ), I just took the description from the excel document with spells.
