### ISSUE TITLE
Spell: Half salary

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#20]
Create a spell that *until the next salary* will decrease the salary gained from all stations by 50%.

- Event: `spell:stations:half-salary`
- Payload: `{}`

This spell should broadcast `stations:half-salary` with a payload of `{}` to everyone in the game. 

Upon the next game tick (salary) it should broadcast `stations:half-salary:faded` to everyone within a game (no payload, ie. `{}`).

*This broadcast might not be needed in the future.*

**Comment by trumtomte** [comment]
This should also (later on) broadcast the new "next salary" value for all teams.

**Comment by petterekedahl** [comment]
How will we know that a tick has "gone off", will we send something from the client or will we have a countdown in our state somehow? :)

**Comment by trumtomte** [comment]
Have the spell (on the next tick) broadcast (to everyone within a game): `stations:half-salary:faded` (no payload). I updated the description.
