### ISSUE TITLE
Spell: Lock player

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#25]
Create a spell that locks a player (this can be used in different ways in the frontend, eg. let the player play an annoying game, etc.).

- Event: `spell:lock:player`
- Payload: `{ playerId, duration }` (the player ID, the duration in seconds)

This spell should use `context.sendTo` in order so send this message to a client with:

- Event: `player:locked`
- Payload: `{ playerId, duration }`

Then a `setTimeout` should be set based on `duration` and after this duration it should unlock the player and then use `context.sendTo` to notify the player (again) with:

- Event:  `player:unlocked`
- Payload: `{ playerId }`

*Some checks can be done like verifying that the user isn't locked already.*

**Comment by kajsaojala** [comment]
Jag tar denna tillsammans med @jasminejasses
