### ISSUE TITLE
Spell: Unlock player

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#26]
Create a spell that unlocks a locked player.

- Event: `spell:unlock:player`
- Payload: `{ playerId }` (the player ID)

This spell should use `context.sendTo` to the player and notify them with:

- Event: `unlock:player`
- Payload: `{ playerId }`

*If the player is already unlocked the spell can fail silently (ie. do nothing).*

**Comment by kajsaojala** [comment]
Jag tar denna tillsammans med @jasminejasses
