### ISSUE TITLE
Spell: Increased login time (player)

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#28]
Create a spell that increases the login time for a player for 1 minute (duration might change in the future).

- Event: `spell:player:slow`
- Payload: `{ playerId }`

This would use `context.sendTo` to notify a player that they've been *slowed* (longer login time):

- Event: `player:slowed`
- Payload: `{ duration }` (it will, for now, always be 1 minute in seconds)

It would at the same time use `setTimeout` for 1 minute and after this, once again, notify the player with:

- Event: `player:slowed:faded`
- Payload: `{}`

**Comment by petterekedahl** [comment]
Should I also make an event for the recieving player (which the spell has been cast onto), or should all of that be handled by the client later on?

**Comment by trumtomte** [comment]
In the issue you'll note `context.sendTo` which is the function that will send the event to a player. So that is already taken care of inside of this handler. If I'm understanding you correctly.

**Comment by petterekedahl** [comment]
I just realized I wasn't thinking straight when I wrote that comment - Everythings fine..
