### ISSUE TITLE
Calculate team salaries of a station

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#37]
Based on our Game State, create a function that calculates the coming salary for each team based on what tokens they have in **one** station. This function should consider the properties `salaryMultiplier` of both the station and the team.

The function should be placed within `calculator.js`. This function should take two arguments: the game state and what station to calculate the salaries from.

The return value is up for discussion but perhaps something along the lines of:

``` js
// Keys are team indexes and values are next salary value
{
  0: 5, // First team is currently getting "5" points next salary
  1: 7, // Second team gets 7
  2: 5, // etc...
  3: 10
}
```

**Comment by petterekedahl** [comment]
Would we be able to build on top of the "calculate team salaries" function? Or do we want to be able to call for the function with a specific station in mind? If so how would we recognize the station, by name or id (there is no id prop in the STATE what I've seen)?

If we decide to just build upon the "calculate team salaires" maybe we would be able to return an object with something like 
{
  0: { 0: 7, 1: 4, 2, 5},
  1: { 0: 7, 1: 4, 2, 5},
  2: { 0: 7, 1: 4, 2, 5},
  total: {0: 21, 1: 12, 2: 15}
}
or would that be confusing using numbers as both "station ids" and teams? My example would be that the big object's keys is the stations, and then the last one would be the total, and then each station the number would represent the team.

It might just be easier to handle the data with a different function the more I think of this..

**Comment by trumtomte** [comment]
Great suggestion! However; sometimes we only need to get the updated salary of a station, eg. when a user swaps a token inside a station. Your suggestion would work in this case but my reasoning for having two separate functions is yours calculates a lot more, which might not be an issue since we're not dealing with lots of data (performance).

As for recognising a station; we've got the station index for that.
