### ISSUE TITLE
Player leaves a game

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#7]
Create an *Event Handler* that removes a player from a game, **not** a team.

- Event `game:leave`
- Payload (which the frontend sends) `{ gameId }` (might not be needed, but lets start by having it).

The handler should broadcast `player:left` with `{ playerId, name }` to all players within the game.

**NOTE:** the player will have to be removed from the `game.players` object.

**Comment by LudvigStridsberg** [comment]
@trumtomte Question: What name are you referring to in the broadcast? The player's name or the game's?

**Comment by trumtomte** [comment]
The player's name 👍
