### ISSUE TITLE
HTTP Server: support for assets (images etc.)

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#70]
Make another `app.use(express.static('dist'));` but for a new folder (lets call it "assets") that will be where we serve images for planets, tokens, etc.

(Inside of `http-server.js`)

Then start adding the images we have from Google Drive.

**Comment by louiseedstrom-zz** [comment]
Do we maybe want sub-folders for planets and tokens and stuff? Or should we just grab it all from the same folder? :)

**Comment by louiseedstrom-zz** [comment]
This will probably be put on ice as we wait for all the images to uploaded

**Comment by trumtomte** [comment]
You can still make this, but just with some example image. So when the images arrives we wont have to wait for it to be developed :D
