### ISSUE TITLE
PRE-GAME: Planningphase

### ISSUE THREAD

**Issue by VilmaNilsson** [VilmaNilsson/VIP2021-game#76]
MORE TIMEASUMING.
The page where each player chooses their actions. Follow the design as good as you can, but make changes if you feel like it (we want 4 instead of 2 actions chosen). Do the timer for the phase and also showcase what team they belong in, and of course all actions (and how they choose one).
REMEMBER:
- Create functions necessary for the issue
- Design the page according to the design (see image)
- Code in the right file/files (e.g. plan.js). Before you code, see if there is any comments/Todo's in your files and do them as well. 

![06 - PlanPhaseView](https://user-images.githubusercontent.com/77903212/116422088-afc10280-a83f-11eb-8f23-bb04e1a0f701.png)
(All images can be found in our Google drive - development - game views)

**Comment by trumtomte** [comment]
This issue requires the addition of showing the teams (as the current implementation does not contain that, however you can take inspiration from `src/components/teams.js`, as that file is used within the game view).

**Comment by trumtomte** [comment]
Make it so you can select 4 spells as well.
