### ISSUE TITLE
GAME-COMPONENT: Teams

### ISSUE THREAD

**Issue by VilmaNilsson** [VilmaNilsson/VIP2021-game#81]
The components for the scores for each team - for now we don't have a image for the rockets, so do how you like to showcase the points/teams good.
REMEMBER:
- Create functions necessary for the issue
- Design the component according to the design (see image)
- Before you code, see if there is any comments/Todo's in your files and do them as well. 

![07a - PlayPhaseView](https://user-images.githubusercontent.com/77903212/116424893-2ced7700-a842-11eb-9906-c98b56a801b7.png)
(All images can be found in our Google drive - development - game views)

**Comment by pierric62** [comment]
For the moment i have 

![image](https://user-images.githubusercontent.com/48721623/117581542-8f296000-b0fd-11eb-8639-41f8e3adf38f.png)
