### ISSUE TITLE
Player leaves a team

### ISSUE THREAD

**Issue by trumtomte** [VilmaNilsson/VIP2021-game#9]
Create an *Event Handler* that removes a player from a team.

- Event `team:leave`
- Payload (which the frontend sends) `{ }`.

The handler should broadcast `team:left` with `{ playerId, name }` to all players within the game.

**NOTE:** you will have to update the player object (in `game.players`) so the `player.team` property is set to -1 (no team).

**Comment by trumtomte** [comment]
This issue is easier to test if the "player joins a game" issue is done beforehand.

**Comment by lgalonso** [comment]
For the payload should the frontend send playerId or team?
